export var mineData = [
  {
    "creatorName": null,
    "createdAt": "2021-06-03 09:56:11",
    "modifiedAt": null,
    "version": 0,
    "id": "1292756202115170050",
    "enabled": true,
    "icon": "",
    "name": "首页",
    "pid": "0",
    "parentName": null,
    "route": "/index",
    "open": false,
    "expand": false,
    "isIframe": false,
    "children": null,
    "menuSort": 1,
    "hidden": false,
    "iconType": "ICON",
    "iconImage": "",
    "rightsIcon": null,
    "rightsName": null
  },
  {
    "creatorName": null,
    "createdAt": "2021-06-03 09:56:11",
    "modifiedAt": "2021-11-07 09:01:16",
    "version": 2,
    "id": "1296638671054830000",
    "enabled": true,
    "icon": "iconhota",
    "name": "应用大赛集锦",
    "pid": "0",
    "parentName": null,
    "route": "/cmspage?pageId=16270115256300001",
    "open": false,
    "expand": false,
    "isIframe": false,
    "children": null,
    "menuSort": 2,
    "hidden": true,
    "iconType": "ICON",
    "iconImage": "",
    "rightsIcon": "",
    "rightsName": null
  },
  {
    "creatorName": null,
    "createdAt": "2021-06-03 09:56:11",
    "modifiedAt": "2021-11-12 17:19:46",
    "version": 1,
    "id": "1292756302656829950",
    "enabled": true,
    "icon": "",
    "name": "云市场",
    "pid": "0",
    "parentName": null,
    "route": "/goodsList/category/999",
    "open": false,
    "expand": false,
    "isIframe": false,
    "children": [
      {
        "creatorName": null,
        "createdAt": "2021-06-03 09:56:11",
        "modifiedAt": "2021-11-15 16:22:39",
        "version": 2,
        "id": "1292758124121430020",
        "enabled": true,
        "icon": "iconzhongxiaoqiye",
        "name": "轻应用",
        "pid": "1292756302656829950",
        "parentName": "云市场",
        "route": "",
        "open": false,
        "expand": false,
        "isIframe": false,
        "children": [
          {
            "creatorName": null,
            "createdAt": "2021-06-03 09:56:11",
            "modifiedAt": "2021-11-13 12:23:54",
            "version": 1,
            "id": "1294178856328110080",
            "enabled": true,
            "icon": "",
            "name": "合同管理应用",
            "pid": "1292758124121430020",
            "parentName": "轻应用",
            "route": "/projectDetail?project_id=15906630180720000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 3,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-06-03 09:56:11",
            "modifiedAt": "2021-11-13 12:24:01",
            "version": 3,
            "id": "1294178897050599940",
            "enabled": true,
            "icon": "",
            "name": "人事管理应用",
            "pid": "1292758124121430020",
            "parentName": "轻应用",
            "route": "/projectDetail?project_id=15906585230720000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 4,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-06-03 09:56:11",
            "modifiedAt": "2021-11-13 12:24:07",
            "version": 1,
            "id": "1294178966176930050",
            "enabled": true,
            "icon": "",
            "name": "资产管理应用",
            "pid": "1292758124121430020",
            "parentName": "轻应用",
            "route": "/projectDetail?project_id=15906609870770000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 6,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-06-03 09:56:11",
            "modifiedAt": "2021-11-13 12:24:14",
            "version": 2,
            "id": "1294179017225799940",
            "enabled": true,
            "icon": "",
            "name": "费用管理应用",
            "pid": "1292758124121430020",
            "parentName": "轻应用",
            "route": "/projectDetail?project_id=15906627340720000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 7,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-11-22 14:52:09",
            "modifiedAt": "2021-11-22 14:52:17",
            "version": 1,
            "id": "16375639298580000",
            "enabled": true,
            "icon": "",
            "name": "更多",
            "pid": "1292758124121430020",
            "parentName": "轻应用",
            "route": "/goodsList/category/999",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 8,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          }
        ],
        "menuSort": 1,
        "hidden": false,
        "iconType": "ICON",
        "iconImage": "",
        "rightsIcon": "",
        "rightsName": null
      },
      {
        "creatorName": null,
        "createdAt": "2021-11-12 17:13:26",
        "modifiedAt": "2023-10-27 15:41:40",
        "version": 7,
        "id": "16367084058590001",
        "enabled": true,
        "icon": "iconhangyeyun",
        "name": "标准模块",
        "pid": "1292756302656829950",
        "parentName": "云市场",
        "route": "",
        "open": false,
        "expand": false,
        "isIframe": false,
        "children": [
          {
            "creatorName": null,
            "createdAt": "2021-11-12 17:17:12",
            "modifiedAt": "2022-06-16 18:00:50",
            "version": 2,
            "id": "16367086318580000",
            "enabled": true,
            "icon": "",
            "name": "人事标准模块",
            "pid": "16367084058590001",
            "parentName": "标准模块",
            "route": "/projectDetail?project_id=165269387212540000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 1,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-11-12 17:18:58",
            "modifiedAt": "2022-06-16 18:01:07",
            "version": 3,
            "id": "16367087378580000",
            "enabled": true,
            "icon": "",
            "name": "费用标准模块",
            "pid": "16367084058590001",
            "parentName": "标准模块",
            "route": "/projectDetail?project_id=165328733012630000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 2,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-11-12 17:17:51",
            "modifiedAt": "2022-06-16 18:01:42",
            "version": 2,
            "id": "16367086708590000",
            "enabled": true,
            "icon": "",
            "name": "合同标准模块",
            "pid": "16367084058590001",
            "parentName": "标准模块",
            "route": "/projectDetail?project_id=165275456812610000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 3,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-11-12 17:18:11",
            "modifiedAt": "2022-06-16 18:02:09",
            "version": 3,
            "id": "16367086908590000",
            "enabled": true,
            "icon": "",
            "name": "资产标准模块",
            "pid": "16367084058590001",
            "parentName": "标准模块",
            "route": "/projectDetail?project_id=165301064612610000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 4,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-11-22 14:52:33",
            "modifiedAt": "2021-11-22 14:52:39",
            "version": 1,
            "id": "16375639538590000",
            "enabled": true,
            "icon": "",
            "name": "更多",
            "pid": "16367084058590001",
            "parentName": "标准模块",
            "route": "/goodsList/category/999",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 5,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          }
        ],
        "menuSort": 3,
        "hidden": false,
        "iconType": "IMAGE",
        "iconImage": "https://asset.seeyoncloud.com:443/%E6%A0%87%E5%87%86%E6%A8%A1%E5%9D%97%EF%BC%882%E5%80%8D%E5%9B%BE%EF%BC%89_165537361313710000.png",
        "rightsIcon": "",
        "rightsName": null
      },
      {
        "creatorName": null,
        "createdAt": "2021-06-03 09:56:11",
        "modifiedAt": "2023-10-27 15:42:03",
        "version": 3,
        "id": "1294178527293339900",
        "enabled": true,
        "icon": "icondaxingjituan",
        "name": "应用产品",
        "pid": "1292756302656829950",
        "parentName": "云市场",
        "route": "",
        "open": false,
        "expand": false,
        "isIframe": false,
        "children": [
          {
            "creatorName": null,
            "createdAt": "2021-06-03 09:56:11",
            "modifiedAt": "2023-07-05 20:47:09",
            "version": 4,
            "id": "15985449232150000",
            "enabled": true,
            "icon": "",
            "name": "费控管理系统",
            "pid": "1294178527293339900",
            "parentName": "应用产品",
            "route": "https://cloud.seeyon.com/c/highQuality?id=100000",
            "open": true,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 1,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2022-06-16 16:43:36",
            "modifiedAt": "2022-06-16 16:43:36",
            "version": 0,
            "id": "165536901613960000",
            "enabled": true,
            "icon": "",
            "name": "合同管理系统",
            "pid": "1294178527293339900",
            "parentName": "应用产品",
            "route": "/projectDetail?project_id=165304603412610000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 2,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2022-06-16 16:44:10",
            "modifiedAt": "2022-06-16 16:44:10",
            "version": 0,
            "id": "165536904913960000",
            "enabled": true,
            "icon": "",
            "name": "项目综合管理系统",
            "pid": "1294178527293339900",
            "parentName": "应用产品",
            "route": "/projectDetail?project_id=16342042447760000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 3,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-06-03 09:56:11",
            "modifiedAt": "2022-06-16 16:43:01",
            "version": 2,
            "id": "1294178729261669890",
            "enabled": true,
            "icon": "",
            "name": "资产管理系统",
            "pid": "1294178527293339900",
            "parentName": "应用产品",
            "route": "/projectDetail?project_id=16365282988240000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 4,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2021-11-22 14:51:58",
            "modifiedAt": "2021-11-22 14:51:58",
            "version": 0,
            "id": "16375639188580000",
            "enabled": true,
            "icon": "",
            "name": "更多",
            "pid": "1294178527293339900",
            "parentName": "应用产品",
            "route": "/goodsList/category/999",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 5,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          }
        ],
        "menuSort": 4,
        "hidden": false,
        "iconType": "ICON",
        "iconImage": "",
        "rightsIcon": "",
        "rightsName": null
      },
      {
        "creatorName": null,
        "createdAt": "2023-10-27 15:40:56",
        "modifiedAt": "2023-11-17 15:29:01",
        "version": 3,
        "id": "169839245522580000",
        "enabled": true,
        "icon": "",
        "name": "供给侧产品",
        "pid": "1292756302656829950",
        "parentName": "云市场",
        "route": "",
        "open": false,
        "expand": false,
        "isIframe": false,
        "children": [
          {
            "creatorName": null,
            "createdAt": "2023-10-27 15:43:27",
            "modifiedAt": "2023-10-27 15:43:27",
            "version": 0,
            "id": "169839260622620000",
            "enabled": true,
            "icon": "",
            "name": "建筑自营-项目成本管理专版",
            "pid": "169839245522580000",
            "parentName": "供给侧产品",
            "route": "/projectDetail?project_id=169294902021960000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 2,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2023-10-27 15:43:53",
            "modifiedAt": "2023-11-17 15:02:33",
            "version": 1,
            "id": "169839263222580000",
            "enabled": true,
            "icon": "",
            "name": "进出口贸易-贸易综合管理专版",
            "pid": "169839245522580000",
            "parentName": "供给侧产品",
            "route": "/projectDetail?project_id=169569049222090000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 3,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2023-11-17 14:09:06",
            "modifiedAt": "2023-12-01 10:25:46",
            "version": 6,
            "id": "170020134523210000",
            "enabled": true,
            "icon": "",
            "name": "商业服务-律所业务综合管理专版",
            "pid": "169839245522580000",
            "parentName": "供给侧产品",
            "route": "/projectDetail?project_id=169838014822880000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 3,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2023-10-27 15:42:29",
            "modifiedAt": "2023-12-01 10:25:49",
            "version": 5,
            "id": "169839254822580000",
            "enabled": true,
            "icon": "",
            "name": "商业服务-经营性资产综合管理专版",
            "pid": "169839245522580000",
            "parentName": "供给侧产品",
            "route": "/projectDetail?project_id=170108064723290000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 4,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2023-11-17 14:59:01",
            "modifiedAt": "2023-11-17 15:19:40",
            "version": 2,
            "id": "170020434123190000",
            "enabled": true,
            "icon": "",
            "name": "更多",
            "pid": "169839245522580000",
            "parentName": "供给侧产品",
            "route": "/goodsList/category/999",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 5,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          }
        ],
        "menuSort": 4,
        "hidden": false,
        "iconType": "IMAGE",
        "iconImage": "https://asset.seeyoncloud.com:443/%E4%BE%9B%E7%BB%99%E4%BE%A7%E5%95%86%E5%93%81%403x_170020613721350000.png",
        "rightsIcon": "",
        "rightsName": null
      },
      {
        "creatorName": null,
        "createdAt": "2022-04-12 15:05:24",
        "modifiedAt": "2023-11-17 14:23:00",
        "version": 5,
        "id": "164974712311710000",
        "enabled": true,
        "icon": "",
        "name": "服务产品",
        "pid": "1292756302656829950",
        "parentName": "云市场",
        "route": "",
        "open": false,
        "expand": false,
        "isIframe": false,
        "children": [
          {
            "creatorName": null,
            "createdAt": "2022-04-12 15:08:11",
            "modifiedAt": "2023-06-25 18:27:47",
            "version": 3,
            "id": "164974729111690000",
            "enabled": true,
            "icon": "",
            "name": "原厂OS在线服务",
            "pid": "164974712311710000",
            "parentName": "服务产品",
            "route": "/projectDetail?project_id=164964454612170000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 1,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          },
          {
            "creatorName": null,
            "createdAt": "2022-04-12 15:07:47",
            "modifiedAt": "2023-06-25 17:10:09",
            "version": 2,
            "id": "164974726611690000",
            "enabled": true,
            "icon": "",
            "name": "原厂增值服务",
            "pid": "164974712311710000",
            "parentName": "服务产品",
            "route": "/projectDetail?project_id=164941133412170000",
            "open": false,
            "expand": false,
            "isIframe": false,
            "children": null,
            "menuSort": 3,
            "hidden": false,
            "iconType": "ICON",
            "iconImage": "",
            "rightsIcon": "",
            "rightsName": null
          }
        ],
        "menuSort": 5,
        "hidden": false,
        "iconType": "IMAGE",
        "iconImage": "https://asset.seeyoncloud.com:443/%E6%9C%8D%E5%8A%A1%E4%BA%A7%E5%93%81icon%EF%BC%882%E5%80%8D%EF%BC%89_164974736011950000.png",
        "rightsIcon": "",
        "rightsName": null
      }
    ],
    "menuSort": 3,
    "hidden": false,
    "iconType": "ICON",
    "iconImage": "",
    "rightsIcon": "",
    "rightsName": null
  },
  {
    "creatorName": null,
    "createdAt": "2021-09-28 20:45:35",
    "modifiedAt": "2021-11-18 19:53:53",
    "version": 4,
    "id": "16328331357480000",
    "enabled": true,
    "icon": "",
    "name": "解决方案",
    "pid": "0",
    "parentName": null,
    "route": "/solution",
    "open": false,
    "expand": false,
    "isIframe": false,
    "children": null,
    "menuSort": 4,
    "hidden": false,
    "iconType": "ICON",
    "iconImage": "",
    "rightsIcon": "",
    "rightsName": null
  },
  {
    "creatorName": null,
    "createdAt": "2021-06-03 09:56:11",
    "modifiedAt": "2021-11-18 20:00:55",
    "version": 1,
    "id": "1292756413231269890",
    "enabled": true,
    "icon": "",
    "name": "客户案例",
    "pid": "0",
    "parentName": null,
    "route": "/casecenter",
    "open": false,
    "expand": false,
    "isIframe": false,
    "children": null,
    "menuSort": 5,
    "hidden": false,
    "iconType": "ICON",
    "iconImage": "",
    "rightsIcon": "",
    "rightsName": null
  }
]
export var searchDetail = {
  presetWord: '费控管理系统',
  hotWords: [
    '项目综合管理系统',
    '费控管理系统',
    '\n科研项目管理解决方案',
    '建筑行业解决方案'
  ]
}
export var cateTagList = [
  {
    "pid": "0",
    "level": 1,
    "sort": 1,
    "child_list": [],
    "category_id": "6",
    "category_name": "轻应用",
    "short_name": "业务应用",
    "is_visible": 1,
    "category_pic": "https://pic-2-bucket.obs.cn-north-1.myhuaweicloud.com:443/%E5%BA%94%E7%94%A8%E4%BA%A7%E5%93%81_1572661045344270000.png",
    "shop_id": "0",
    "icon_status": 0,
    "category_enum": 1,
    "category_sn": "YY",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "yingyongchanpin_pc",
    "ad_co_mt": "yingyongchanpin_yd",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  },
  {
    "pid": "0",
    "level": 1,
    "sort": 2,
    "child_list": [],
    "category_id": "86",
    "category_name": "标准模块",
    "short_name": "协同",
    "is_visible": 1,
    "category_pic": "",
    "shop_id": "0",
    "icon_status": 0,
    "category_enum": 220,
    "category_sn": "XT",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "xietongpingtai_pc",
    "ad_co_mt": "xietongpingtai_yd",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  },
  {
    "pid": "0",
    "level": 1,
    "sort": 3,
    "child_list": [],
    "category_id": "129",
    "category_name": "应用产品",
    "short_name": "应用产品",
    "is_visible": 1,
    "category_pic": "",
    "shop_id": "0",
    "icon_status": 0,
    "category_enum": 120,
    "category_sn": "yycp",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "",
    "ad_co_mt": "",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  },
  {
    "pid": "0",
    "level": 1,
    "sort": 4,
    "child_list": [],
    "category_id": "69",
    "category_name": "协同平台",
    "short_name": "工具",
    "is_visible": 1,
    "category_pic": "",
    "shop_id": "0",
    "icon_status": 0,
    "category_enum": 110,
    "category_sn": "YYY",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "",
    "ad_co_mt": "",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  },
  {
    "pid": "0",
    "level": 1,
    "sort": 5,
    "child_list": [],
    "category_id": "16639",
    "category_name": "供给侧产品",
    "short_name": "业务应用",
    "is_visible": 1,
    "category_pic": "",
    "shop_id": "0",
    "icon_status": 0,
    "category_enum": 9,
    "category_sn": "gjccp",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "",
    "ad_co_mt": "",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  },
  {
    "pid": "0",
    "level": 1,
    "sort": 6,
    "child_list": [],
    "category_id": "9",
    "category_name": "服务产品",
    "short_name": "服务",
    "is_visible": 1,
    "category_pic": "https://pic-2-bucket.obs.cn-north-1.myhuaweicloud.com:443/%E6%9C%8D%E5%8A%A1%E4%BA%A7%E5%93%81_1572661102620190000.png",
    "shop_id": "0",
    "icon_status": 1,
    "category_enum": 41,
    "category_sn": "FW",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "",
    "ad_co_mt": "",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  },
  {
    "pid": "0",
    "level": 1,
    "sort": 11,
    "child_list": [],
    "category_id": "16633",
    "category_name": "生态产品",
    "short_name": "业务产品",
    "is_visible": 1,
    "category_pic": "",
    "shop_id": "0",
    "icon_status": 0,
    "category_enum": 5,
    "category_sn": "Ecological",
    "access_identity": "1,2",
    "data_type": "4",
    "ad_co_pc": "",
    "ad_co_mt": "",
    "ad_gov_pc": "",
    "ad_gov_mt": ""
  }
]
export var tagList = [
  {
    "group_id": "680",
    "pid": 0,
    "level": 1,
    "description": "适用于企业案例、商品、解决方案",
    "sort": 2,
    "group_name": "行业体系",
    "short_name": "行业体系",
    "is_visible": 1,
    "shop_id": 0,
    "access_identity": "1,3",
    "child_list": [
      {
        "group_id": "2854",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 1,
        "group_name": "通用",
        "short_name": "通用",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "2852",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 10,
        "group_name": "国资体系",
        "short_name": "国资体系",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "689",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 11,
        "group_name": "建筑",
        "short_name": "建筑",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "2724",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 20,
        "group_name": "房地产",
        "short_name": "房地产",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "819",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 30,
        "group_name": "IT服务",
        "short_name": "IT服务",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "682",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 40,
        "group_name": "教育",
        "short_name": "教育",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2744",
            "pid": 682,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "985/211",
            "short_name": "985/211",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2741",
            "pid": 682,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "本科院校",
            "short_name": "本科院校",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2742",
            "pid": 682,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "职业院校",
            "short_name": "职业院校",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2743",
            "pid": 682,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "教育机构",
            "short_name": "教育机构",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2881",
            "pid": 682,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "其他",
            "short_name": "其他",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2266",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 50,
        "group_name": "制造",
        "short_name": "制造",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2799",
            "pid": 2266,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "制造",
            "short_name": "制造",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2745",
            "pid": 2266,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "离散制造",
            "short_name": "离散制造",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2746",
            "pid": 2266,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "流程制造",
            "short_name": "流程制造",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "719",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 60,
        "group_name": "金融",
        "short_name": "金融",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2747",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 10,
            "group_name": "银行",
            "short_name": "银行",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2748",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 20,
            "group_name": "证券",
            "short_name": "证券",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2749",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 30,
            "group_name": "保险",
            "short_name": "保险",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2750",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 40,
            "group_name": "信托",
            "short_name": "信托",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2876",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 50,
            "group_name": "期货",
            "short_name": "期货",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2877",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 60,
            "group_name": "基金",
            "short_name": "基金",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2878",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 70,
            "group_name": "财务公司",
            "short_name": "财务公司",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2879",
            "pid": 719,
            "level": 3,
            "description": "",
            "sort": 80,
            "group_name": "金融",
            "short_name": "金融",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "684",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 70,
        "group_name": "投资运营",
        "short_name": "投资运营",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "2265",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 80,
        "group_name": "科研院所",
        "short_name": "科研院所",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "685",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 90,
        "group_name": "快消品",
        "short_name": "快消品",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2751",
            "pid": 685,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "食品",
            "short_name": "食品",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2752",
            "pid": 685,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "酒",
            "short_name": "酒",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2753",
            "pid": 685,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "饮料",
            "short_name": "饮料",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2800",
            "pid": 685,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "快消品",
            "short_name": "快消品",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2486",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 100,
        "group_name": "商贸流通",
        "short_name": "商贸流通",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2762",
            "pid": 2486,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "零售",
            "short_name": "零售",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2763",
            "pid": 2486,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "百货/专卖",
            "short_name": "百货/专卖",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2764",
            "pid": 2486,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "连锁",
            "short_name": "连锁",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2765",
            "pid": 2486,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "贸易",
            "short_name": "贸易",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2766",
            "pid": 2486,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "商贸流通",
            "short_name": "商贸流通",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2487",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 110,
        "group_name": "医药医疗",
        "short_name": "医药医疗",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2754",
            "pid": 2487,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "医药",
            "short_name": "医药",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2855",
            "pid": 2487,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "医院",
            "short_name": "医院",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2856",
            "pid": 2487,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "医疗卫生",
            "short_name": "医疗卫生",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2857",
            "pid": 2487,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "医疗器械",
            "short_name": "医疗器械",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "815",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 120,
        "group_name": "交通运输",
        "short_name": "交通运输",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2757",
            "pid": 815,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "运输",
            "short_name": "运输",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2758",
            "pid": 815,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "物流",
            "short_name": "物流",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2759",
            "pid": 815,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "仓储",
            "short_name": "仓储",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2760",
            "pid": 815,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "邮政",
            "short_name": "邮政",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2761",
            "pid": 815,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "交通运输",
            "short_name": "交通运输",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "711",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 130,
        "group_name": "现代服务",
        "short_name": "现代服务",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2767",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "餐饮住宿",
            "short_name": "餐饮住宿",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2768",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "租赁",
            "short_name": "租赁",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2769",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "法律服务",
            "short_name": "法律服务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2770",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "咨询服务",
            "short_name": "咨询服务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2771",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "广告服务",
            "short_name": "广告服务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2772",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 6,
            "group_name": "人力资源服务",
            "short_name": "人力资源服务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2773",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 7,
            "group_name": "会议展览",
            "short_name": "会议展览",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2774",
            "pid": 711,
            "level": 3,
            "description": "",
            "sort": 8,
            "group_name": "现代服务",
            "short_name": "现代服务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "683",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 150,
        "group_name": "文化传媒",
        "short_name": "文化传媒",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2775",
            "pid": 683,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "新闻出版",
            "short_name": "新闻出版",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2776",
            "pid": 683,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "广播/电视/电影",
            "short_name": "广播/电视/电影",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2777",
            "pid": 683,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "广告",
            "short_name": "广告",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2778",
            "pid": 683,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "文化传媒",
            "short_name": "文化传媒",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "688",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 160,
        "group_name": "电信",
        "short_name": "电信",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "829",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 170,
        "group_name": "能源",
        "short_name": "能源",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2880",
            "pid": 829,
            "level": 3,
            "description": "",
            "sort": 10,
            "group_name": "电力",
            "short_name": "电力",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2779",
            "pid": 829,
            "level": 3,
            "description": "",
            "sort": 20,
            "group_name": "采矿业",
            "short_name": "采矿业",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2780",
            "pid": 829,
            "level": 3,
            "description": "",
            "sort": 30,
            "group_name": "其他",
            "short_name": "其他",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "835",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 180,
        "group_name": "农林牧渔",
        "short_name": "农林牧渔",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2781",
            "pid": 835,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "农业",
            "short_name": "农业",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2782",
            "pid": 835,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "林业",
            "short_name": "林业",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2783",
            "pid": 835,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "渔业",
            "short_name": "渔业",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2784",
            "pid": 835,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "畜牧业",
            "short_name": "畜牧业",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2785",
            "pid": 835,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "农林牧渔",
            "short_name": "农林牧渔",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "690",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 190,
        "group_name": "公用事业",
        "short_name": "公用事业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2786",
            "pid": 690,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "市政设施",
            "short_name": "市政设施",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2787",
            "pid": 690,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "水务",
            "short_name": "水务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2788",
            "pid": 690,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "燃气",
            "short_name": "燃气",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2789",
            "pid": 690,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "环保",
            "short_name": "环保",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2790",
            "pid": 690,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "公用事业",
            "short_name": "公用事业",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2250",
        "pid": 680,
        "level": 2,
        "description": "",
        "sort": 200,
        "group_name": "其他",
        "short_name": "其他",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2791",
            "pid": 2250,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "烟草",
            "short_name": "烟草",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2792",
            "pid": 2250,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "旅游",
            "short_name": "旅游",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2793",
            "pid": 2250,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "产业园区",
            "short_name": "产业园区",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      }
    ]
  },
  {
    "group_id": "681",
    "pid": 0,
    "level": 1,
    "description": "适用于企业案例、商品、解决方案",
    "sort": 3,
    "group_name": "业务应用",
    "short_name": "业务应用",
    "is_visible": 1,
    "shop_id": 0,
    "access_identity": "1,3",
    "child_list": [
      {
        "group_id": "697",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 1,
        "group_name": "协同平台",
        "short_name": "协同平台",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2801",
            "pid": 697,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "协同平台",
            "short_name": "协同平台",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2802",
            "pid": 697,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "门户",
            "short_name": "门户",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2803",
            "pid": 697,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "BPM流程",
            "short_name": "BPM流程",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2804",
            "pid": 697,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "业务定制",
            "short_name": "业务定制",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "691",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 2,
        "group_name": "协同办公",
        "short_name": "协同办公",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2813",
            "pid": 691,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "协同办公",
            "short_name": "协同办公",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "792",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 3,
        "group_name": "行政",
        "short_name": "行政",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2805",
            "pid": 792,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "行政管理",
            "short_name": "行政管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2806",
            "pid": 792,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "办公用品管理",
            "short_name": "办公用品管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2807",
            "pid": 792,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "车辆管理",
            "short_name": "车辆管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2808",
            "pid": 792,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "接待管理",
            "short_name": "接待管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "692",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 4,
        "group_name": "人力",
        "short_name": "人力",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2809",
            "pid": 692,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "人事管理",
            "short_name": "人事管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2810",
            "pid": 692,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "人力资源",
            "short_name": "人力资源",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2811",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 5,
        "group_name": "费控",
        "short_name": "费控",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2814",
            "pid": 2811,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "费控管理",
            "short_name": "费控管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2815",
            "pid": 2811,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "商旅服务",
            "short_name": "商旅服务",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "820",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 6,
        "group_name": "财务",
        "short_name": "财务",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2816",
            "pid": 820,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "财务管理",
            "short_name": "财务管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2817",
            "pid": 820,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "财务共享",
            "short_name": "财务共享",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2818",
            "pid": 820,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "业财一体化",
            "short_name": "业财一体化",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "707",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 6,
        "group_name": "合同",
        "short_name": "合同",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2819",
            "pid": 707,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "合同管理",
            "short_name": "合同管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "694",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 7,
        "group_name": "资产",
        "short_name": "资产",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2820",
            "pid": 694,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "资产管理",
            "short_name": "资产管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "708",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 8,
        "group_name": "销售",
        "short_name": "销售",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2821",
            "pid": 708,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "客户管理",
            "short_name": "客户管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2822",
            "pid": 708,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "销售管理",
            "short_name": "销售管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2823",
            "pid": 708,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "营销管理",
            "short_name": "营销管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2824",
            "pid": 708,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "门店管理",
            "short_name": "门店管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "696",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 9,
        "group_name": "项目",
        "short_name": "项目",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2825",
            "pid": 696,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "项目管理",
            "short_name": "项目管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "698",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 10,
        "group_name": "采购",
        "short_name": "采购",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2826",
            "pid": 698,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "采购管理",
            "short_name": "采购管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "793",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 11,
        "group_name": "供应商",
        "short_name": "供应商",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2827",
            "pid": 793,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "供应商管理",
            "short_name": "供应商管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2812",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 11,
        "group_name": "生产",
        "short_name": "生产",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2828",
            "pid": 2812,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "生产管理",
            "short_name": "生产管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "816",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 12,
        "group_name": "法务合规",
        "short_name": "法务合规",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2829",
            "pid": 816,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "法务管理",
            "short_name": "法务管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2830",
            "pid": 816,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "合规管理",
            "short_name": "合规管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2831",
            "pid": 816,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "法务合规",
            "short_name": "法务合规",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "710",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 13,
        "group_name": "文会事",
        "short_name": "文会事",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2832",
            "pid": 710,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "公文管理",
            "short_name": "公文管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2833",
            "pid": 710,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "会议管理",
            "short_name": "会议管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2834",
            "pid": 710,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "督查督办",
            "short_name": "督查督办",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2835",
            "pid": 710,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "文会事",
            "short_name": "文会事",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "817",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 14,
        "group_name": "党建",
        "short_name": "党建",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2836",
            "pid": 817,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "党建管理",
            "short_name": "党建管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2837",
            "pid": 817,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "工会管理",
            "short_name": "工会管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "791",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 15,
        "group_name": "监督监管",
        "short_name": "监督监管",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2838",
            "pid": 791,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "监督追责",
            "short_name": "监督追责",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2839",
            "pid": 791,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "风险管理",
            "short_name": "风险管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2840",
            "pid": 791,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "审计管理",
            "short_name": "审计管理",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2841",
            "pid": 791,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "三重一大",
            "short_name": "三重一大",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2842",
            "pid": 791,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "监督监管",
            "short_name": "监督监管",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "823",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 16,
        "group_name": "投资运营",
        "short_name": "投资运营",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2843",
            "pid": 823,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "投资运营",
            "short_name": "投资运营",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "703",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 17,
        "group_name": "数据分析",
        "short_name": "数据分析",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2844",
            "pid": 703,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "数据分析",
            "short_name": "数据分析",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2845",
            "pid": 703,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "BI分析",
            "short_name": "BI分析",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2796",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 18,
        "group_name": "系统集成",
        "short_name": "系统集成",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2846",
            "pid": 2796,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "系统集成",
            "short_name": "系统集成",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2847",
            "pid": 2796,
            "level": 3,
            "description": "",
            "sort": 2,
            "group_name": "ERP集成",
            "short_name": "ERP集成",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2848",
            "pid": 2796,
            "level": 3,
            "description": "",
            "sort": 3,
            "group_name": "DEE集成",
            "short_name": "DEE集成",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2849",
            "pid": 2796,
            "level": 3,
            "description": "",
            "sort": 4,
            "group_name": "门户集成",
            "short_name": "门户集成",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          },
          {
            "group_id": "2850",
            "pid": 2796,
            "level": 3,
            "description": "",
            "sort": 5,
            "group_name": "移动集成",
            "short_name": "移动集成",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2797",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 19,
        "group_name": "创新应用",
        "short_name": "创新应用",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": [
          {
            "group_id": "2851",
            "pid": 2797,
            "level": 3,
            "description": "",
            "sort": 1,
            "group_name": "创新应用",
            "short_name": "创新应用",
            "is_visible": 1,
            "shop_id": 0,
            "access_identity": "1,3",
            "child_list": []
          }
        ]
      },
      {
        "group_id": "2798",
        "pid": 681,
        "level": 2,
        "description": "",
        "sort": 20,
        "group_name": "其他",
        "short_name": "其他",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      }
    ]
  },
  {
    "group_id": "417",
    "pid": 0,
    "level": 1,
    "description": "适用于企业商品、案例、主题空间",
    "sort": 10,
    "group_name": "行业体系",
    "short_name": "行业体系",
    "is_visible": 1,
    "shop_id": 0,
    "access_identity": "1",
    "child_list": [
      {
        "group_id": "805",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 10,
        "group_name": "通用",
        "short_name": "通用",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "420",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 20,
        "group_name": "国资体系",
        "short_name": "国资体系",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "428",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 30,
        "group_name": "医药医疗",
        "short_name": "医药医疗",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "421",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 40,
        "group_name": "建筑行业",
        "short_name": "建筑行业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "834",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 50,
        "group_name": "高校院所",
        "short_name": "高校院所",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2492",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 51,
        "group_name": "金融行业",
        "short_name": "金融行业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2493",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 52,
        "group_name": "IT服务行业",
        "short_name": "IT服务行业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2494",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 53,
        "group_name": "汽配行业",
        "short_name": "汽配行业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2719",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 54,
        "group_name": "交通运输",
        "short_name": "交通运输",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2720",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 55,
        "group_name": "科研院所",
        "short_name": "科研院所",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2721",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 56,
        "group_name": "制造业",
        "short_name": "制造业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2722",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 57,
        "group_name": "商务服务业",
        "short_name": "商务服务业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "806",
        "pid": 417,
        "level": 2,
        "description": "",
        "sort": 60,
        "group_name": "其他行业",
        "short_name": "其他行业",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      }
    ]
  },
  {
    "group_id": "418",
    "pid": 0,
    "level": 1,
    "description": "适用于企业商品、案例、主题空间",
    "sort": 20,
    "group_name": "业务应用",
    "short_name": "业务应用",
    "is_visible": 1,
    "shop_id": 0,
    "access_identity": "1",
    "child_list": [
      {
        "group_id": "729",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 0,
        "group_name": "防疫管理",
        "short_name": "防疫管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "796",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 1,
        "group_name": "医药医疗专区商品",
        "short_name": "医药医疗专区商品",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "831",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 1,
        "group_name": "协同办公",
        "short_name": "协同办公",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2723",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 2,
        "group_name": "投资管理",
        "short_name": "投资管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2727",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 6,
        "group_name": "监督追责",
        "short_name": "监督追责",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2853",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 7,
        "group_name": "督查督办",
        "short_name": "督查督办",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2728",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 8,
        "group_name": "会议管理",
        "short_name": "会议管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2729",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 8,
        "group_name": "公文管理",
        "short_name": "公文管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "2726",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 10,
        "group_name": "公务车管理",
        "short_name": "公务车管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "432",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 10,
        "group_name": "行政管理",
        "short_name": "行政管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "430",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 20,
        "group_name": "人力资源",
        "short_name": "人力资源",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "838",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 21,
        "group_name": "资产管理",
        "short_name": "资产管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "802",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 25,
        "group_name": "合同管理",
        "short_name": "合同管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "433",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 30,
        "group_name": "费控管理",
        "short_name": "费控管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "436",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 35,
        "group_name": "项目管理",
        "short_name": "项目管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "435",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 40,
        "group_name": "销售管理",
        "short_name": "销售管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "434",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 50,
        "group_name": "采购管理",
        "short_name": "采购管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "832",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 60,
        "group_name": "招投标管理",
        "short_name": "招投标管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "803",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 75,
        "group_name": "任务管理",
        "short_name": "任务管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "600",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 80,
        "group_name": "生产管理",
        "short_name": "生产管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "833",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 85,
        "group_name": "系统集成",
        "short_name": "系统集成",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "801",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 90,
        "group_name": "法务管理",
        "short_name": "法务管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "431",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 90,
        "group_name": "运营管理",
        "short_name": "运营管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "665",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 100,
        "group_name": "库存管理",
        "short_name": "库存管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "605",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 110,
        "group_name": "市场管理",
        "short_name": "市场管理",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      },
      {
        "group_id": "804",
        "pid": 418,
        "level": 2,
        "description": "",
        "sort": 130,
        "group_name": "其他",
        "short_name": "其他",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1",
        "child_list": []
      }
    ]
  },
  {
    "group_id": "807",
    "pid": 0,
    "level": 1,
    "description": "适用于企业商品",
    "sort": 30,
    "group_name": "产品系列",
    "short_name": "产品系列",
    "is_visible": 1,
    "shop_id": 0,
    "access_identity": "1,3",
    "child_list": [
      {
        "group_id": "808",
        "pid": 807,
        "level": 2,
        "description": "",
        "sort": 20,
        "group_name": "A8+",
        "short_name": "A8+",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "839",
        "pid": 807,
        "level": 2,
        "description": "",
        "sort": 25,
        "group_name": "A8-N",
        "short_name": "A8-N",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "809",
        "pid": 807,
        "level": 2,
        "description": "",
        "sort": 30,
        "group_name": "A6+",
        "short_name": "A6+",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      },
      {
        "group_id": "810",
        "pid": 807,
        "level": 2,
        "description": "",
        "sort": 50,
        "group_name": "G6",
        "short_name": "G6",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,3",
        "child_list": []
      }
    ]
  },
  {
    "group_id": "764",
    "pid": 0,
    "level": 1,
    "description": "适用于政企商品",
    "sort": 99,
    "group_name": "商品归属",
    "short_name": "商品归属",
    "is_visible": 1,
    "shop_id": 0,
    "access_identity": "1,2",
    "child_list": [
      {
        "group_id": "840",
        "pid": 764,
        "level": 2,
        "description": "",
        "sort": 1,
        "group_name": "致远互联",
        "short_name": "致远互联",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,2",
        "child_list": []
      },
      {
        "group_id": "841",
        "pid": 764,
        "level": 2,
        "description": "",
        "sort": 2,
        "group_name": "第三方",
        "short_name": "第三方",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,2",
        "child_list": []
      },
      {
        "group_id": "2892",
        "pid": 764,
        "level": 2,
        "description": "",
        "sort": 3,
        "group_name": "供给侧精品",
        "short_name": "供给侧精品",
        "is_visible": 1,
        "shop_id": 0,
        "access_identity": "1,2",
        "child_list": []
      }
    ]
  }
]